# CMake generated Testfile for 
# Source directory: /home/puya/Projects/flower_anydsl/apps
# Build directory: /home/puya/Projects/flower_anydsl/build/apps
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(bilateral "bilateral")
set_tests_properties(bilateral PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;156;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(bilateral_burst "bilateral_burs")
set_tests_properties(bilateral_burst PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;166;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(box_filter "box_filter")
set_tests_properties(box_filter PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;176;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(box_filter_burst "box_filter_burst")
set_tests_properties(box_filter_burst PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;186;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(laplace "laplace")
set_tests_properties(laplace PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;196;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(laplace_burst "laplace_burst")
set_tests_properties(laplace_burst PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;206;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(gaussian "gaussian")
set_tests_properties(gaussian PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;216;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(gaussian_burst "gaussian_burst")
set_tests_properties(gaussian_burst PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;226;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(sobel_luma "sobel_luma")
set_tests_properties(sobel_luma PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;236;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(sobel_luma_burst "sobel_luma_burst")
set_tests_properties(sobel_luma_burst PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;246;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(sobel_burst "sobel_burst")
set_tests_properties(sobel_burst PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;256;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(unsharp "unsharp")
set_tests_properties(unsharp PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;266;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(optical_flow_hs "optical_flow_hs")
set_tests_properties(optical_flow_hs PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;276;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(optical_flow_lk "optical_flow_lk")
set_tests_properties(optical_flow_lk PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;286;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(jacobi "jacobi")
set_tests_properties(jacobi PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;296;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(jacobi_burst "jacobi_aie")
set_tests_properties(jacobi_burst PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;306;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(square "square")
set_tests_properties(square PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;316;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(square_burst "square_burst")
set_tests_properties(square_burst PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;326;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(posterization_burst_mosaic "posterization_burst_mosaic")
set_tests_properties(posterization_burst_mosaic PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;391;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(posterization_burst "posterization_burst")
set_tests_properties(posterization_burst PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;402;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(box_filter_aie "box_filter_aie")
set_tests_properties(box_filter_aie PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;455;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(square_aie "square_aie_spmd")
set_tests_properties(square_aie PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;475;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(sobel_aie "sobel_aie")
set_tests_properties(sobel_aie PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;497;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(sobel_luma_aie "sobel_luma_aie")
set_tests_properties(sobel_luma_aie PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;507;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(unsharp_aie "unsharp_aie")
set_tests_properties(unsharp_aie PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;567;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(unsharp_aie_split "unsharp_aie_split")
set_tests_properties(unsharp_aie_split PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;578;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(unsharp_aie_split_fused "unsharp_aie_split_fused")
set_tests_properties(unsharp_aie_split_fused PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;589;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(posterization_hetero "posterization_hetero")
set_tests_properties(posterization_hetero PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;601;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(posterization_aie "posterization_aie")
set_tests_properties(posterization_aie PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;611;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(posterization_aie_spmd "posterization_aie_spmd")
set_tests_properties(posterization_aie_spmd PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;622;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(posterization_aie_single "posterization_aie_single")
set_tests_properties(posterization_aie_single PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;633;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
add_test(paper_example "paper_example")
set_tests_properties(paper_example PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;645;add_test;/home/puya/Projects/flower_anydsl/apps/CMakeLists.txt;0;")
