# CMake generated Testfile for 
# Source directory: /home/puya/Projects/flower_anydsl/test
# Build directory: /home/puya/Projects/flower_anydsl/build/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(fpga_copy "test_fpga_copy")
set_tests_properties(fpga_copy PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;10;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(fpga_cgra_dataflow "test_fpga_cgra_dataflow")
set_tests_properties(fpga_cgra_dataflow PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;20;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(fpga_multi_kernel_cgra_dataflow "test_fpga_multi_kernel_cgra_dataflow")
set_tests_properties(fpga_multi_kernel_cgra_dataflow PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;30;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(fpga_cgra_vectorized "test_fpga_cgra_vectorized")
set_tests_properties(fpga_cgra_vectorized PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;40;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(fpga_cgra_vectorized_scaled "test_fpga_cgra_vectorized_scaled")
set_tests_properties(fpga_cgra_vectorized_scaled PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;51;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(fpga_cgra_vectorized_scaled2 "test_fpga_cgra_vectorized_scaled2")
set_tests_properties(fpga_cgra_vectorized_scaled2 PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;61;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(fpga_cgra_vectorized_scaled2_stream "test_fpga_cgra_vectorized_scaled2_stream")
set_tests_properties(fpga_cgra_vectorized_scaled2_stream PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;72;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(fpga_cgra_vectorized_scaled2_window "test_fpga_cgra_vectorized_scaled2_window")
set_tests_properties(fpga_cgra_vectorized_scaled2_window PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;82;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(fpga_cgra_vectorized_scaled3 "test_fpga_cgra_vectorized_scaled3")
set_tests_properties(fpga_cgra_vectorized_scaled3 PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;95;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(fpga_cgra_vectorized_scaled_byReplication "test_fpga_cgra_vectorized_scaled_byReplication")
set_tests_properties(fpga_cgra_vectorized_scaled_byReplication PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;106;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(fpga_cgra_vectorized_scaled_byReplication2 "test_fpga_cgra_vectorized_scaled_byReplication2")
set_tests_properties(fpga_cgra_vectorized_scaled_byReplication2 PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;117;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(dataflow "test_dataflow")
set_tests_properties(dataflow PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;128;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(loop_pipeline "test_loop_pipeline")
set_tests_properties(loop_pipeline PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;139;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(lp_nested "test_reserve_shared")
set_tests_properties(lp_nested PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;149;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(test_fir_vectorized "test_fir_vectorized")
set_tests_properties(test_fir_vectorized PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;169;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(test_fir2d_vect_nobh "test_fir2d_vect_nobh")
set_tests_properties(test_fir2d_vect_nobh PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;179;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(test_fir2d_vect_nobh_abs "test_fir2d_vect_nobh_abs")
set_tests_properties(test_fir2d_vect_nobh_abs PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;189;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(test_fir2d_vect_nobh_abs_v2 "test_fir2d_vect_nobh_abs_v2")
set_tests_properties(test_fir2d_vect_nobh_abs_v2 PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;199;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(test_fir2d_vect_nobh_flat_mask "test_fir2d_vect_nobh_flat_mask")
set_tests_properties(test_fir2d_vect_nobh_flat_mask PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;209;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(test_fir2d_vect_nobh_flat_mask_pl_pingpong "test_fir2d_vect_nobh_flat_mask_pl_pingpong")
set_tests_properties(test_fir2d_vect_nobh_flat_mask_pl_pingpong PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;219;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(test_fir2d_vect_nobh_flat_mask_pl_aie_pingpong "test_fir2d_vect_nobh_flat_mask_pl_aie_pingpong")
set_tests_properties(test_fir2d_vect_nobh_flat_mask_pl_aie_pingpong PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;229;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(test_fir2d_vect_nobh_flat_mask_pl_aie_pingpong_opt "test_fir2d_vect_nobh_flat_mask_pl_aie_pingpong_opt")
set_tests_properties(test_fir2d_vect_nobh_flat_mask_pl_aie_pingpong_opt PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;240;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(test_fir2d_vect_nobh_flat_mask_pl_aie_pingpong_scaled "test_fir2d_vect_nobh_flat_mask_pl_aie_pingpong_scaled")
set_tests_properties(test_fir2d_vect_nobh_flat_mask_pl_aie_pingpong_scaled PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;251;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
add_test(test_fir2d_vect_nobh_flat_mask_stream "test_fir2d_vect_nobh_flat_mask_stream")
set_tests_properties(test_fir2d_vect_nobh_flat_mask_stream PROPERTIES  _BACKTRACE_TRIPLES "/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;263;add_test;/home/puya/Projects/flower_anydsl/test/CMakeLists.txt;0;")
